config/routes.rb
Rails.application.routes.draw do
  root 'musics#index'
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}
  resources :lists
  resources :musics
  resources :resources
  get 'cadastrar' => 'users#new', as: :cadastrar

  get 'lists/:id/add_music' => 'lists#add_music', as: :add_music
  get 'lists/:id/remove_music' => 'lists#remove_music', as: :remove_music

  get 'musics/:id/rate_music' => 'musics#rate_music', as: :rate_music

  get 'users/musics' => 'users#musics'

  resources :users

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resources</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>