config/routes.rb
Rails.application.routes.draw do
  root 'musics#index'
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}
  resources :lists
  resources :musics
  resources :resources
  get 'cadastrar' => 'users#new', as: :cadastrar

  get 'lists/:id/add_music' => 'lists#add_music', as: :add_music
  get 'lists/:id/remove_music' => 'lists#remove_music', as: :remove_music

  get 'musics/:id/rate_music' => 'musics#rate_music', as: :rate_music

  get 'users/musics' => 'users#musics'

  resources :users

end

app/models/music.rb
class Music < ActiveRecord::Base
  require 'open-uri'
  require 'nokogiri'

  before_create :generate_uris, :normalize_names

  belongs_to :user, foreign_key: 'sent_by_id'
  belongs_to :genre
  has_and_belongs_to_many :lists
  has_many :resources

  validates :name, :artist, :genre, presence: true

  def normalize_names
    self.name = self.name.downcase
    self.artist = self.artist.downcase
  end

  def generate_uris
    begin
      self.get_youtube_link
      self.create_spotify_audio
    rescue => e
      logger.debug "ERRO AO TENTAR GERAR YOUTUBE LINK OU SPOTIFY AUDIO"
      logger.debug e.inspect
    end
  end

  def youtube_iframe
    return nil unless youtube_link
    'https://www.youtube.com/embed/' + youtube_link

    # example youtube link
    # https://www.youtube.com/watch?v=cn0S56WPkjQ&sa=U&ved=0ahUKEwiwkN76x6jLAhXKiJAKHTwsAukQtwIIHjAB&usg=AFQjCNG9AowpsKn1Cn1jJvYXe0ZU16l8aw
  end

  def spotify_iframe
    return nil unless spotify_track
    'https://embed.spotify.com/?uri=' + spotify_track
  end

  def get_first_link(q)
    uri = 'http://www.google.com/search?num=3&q=' + URI.escape(q)

    open(uri) do |page|
      html = Nokogiri::HTML page
      pattern = /http.+\//
      html.css('h3.r a').first['href'][pattern]
    end
  end

  def get_youtube_link
    art = self.artist.downcase
    music = self.name.downcase

    q = 'youtube+br+' + art.gsub(/( & | e |\s)/, '+') + music.gsub(/\s/, '+')
    uri = 'http://www.google.com/search?num=3&q=' + URI.escape(q)

    # begin
    open(uri) do |page|
      html = Nokogiri::HTML page

      link = html.css('h3.r a').first['href']
      link = URI.unescape(link)[/http.+/]
      link = URI.unescape(link)[/v=([A-Z])*\w+/]

      unless link.nil?
        self.youtube_link = link[2, link.length - 1]
      end
    end
  end

  def create_spotify_audio
    require 'nokogiri'
    require 'httparty'

    art = self.artist.gsub(/\s/, '+').downcase
    music = self.name.gsub(/\s/, '+').downcase
    url = 'http://api.spotify.com/v1/search/?type=track&limit=1&q=' + art + '+' + music

    data = HTTParty.get(url, verify: false)

    parsed_response = JSON.parse(data.body)

    if parsed_response['tracks']['total'] > 1
      self.spotify_track = parsed_response['tracks']['items'][0]['uri']
    end
  end
end

app/controllers/musics_controller.rb
# musics controller
# rubocop:disable Style/IndentationConsistency, Metrics/MethodLength
class MusicsController < ApplicationController
  before_action :set_music, only: [:edit, :show, :update, :destroy, :rate_music]
  # before_action :logged_in_only
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
    @music = Music.new
  end

  def edit
  end

  def index
    if(query = params[:q])
      @musics = search_musics(query).paginate(page: params[:page], per_page: 50)
    else
      @musics = Music.paginate(page: params[:page], per_page: 50)
    end
  end

  def create
    @music = Music.new(music_params)
    @music.num_views = 0

    if (user = current_user)
      @music.sent_by_id = user.id
    end

    if @music.save
      Resource.generate_resources(@music)
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @music.update_attributes(music_params)
      redirect_to action: 'index'
    else
      flash[:danger] = 'Erro ao salvar música'
    end
  end

  def destroy
    if @music.destroy
      redirect_to root_url
    else
      flash[:danger] = 'Erro ao deletar música'
    end
  end

  def rate_music
    session[:forwarding_url] = request.referrer

    rate = params['rate'].to_i
    current_rate = @music.rating || 0
    current_total = current_rate * @music.rating_count

    flash[:danger] = 'rate is nil' if rate.nil?
    flash[:danger] = 'current_rate is nil' if current_rate.nil?
    flash[:danger] = 'current_total is nil' if current_total.nil?
    flash[:danger] = 'rating_count is nil' if @music.rating_count.nil?

    unless rate.nil? || current_rate.nil? || current_total.nil?
      new_rating_count = @music.rating_count + 1
      new_rate = (current_total + rate) / new_rating_count

      @music.update_attributes(rating: new_rate, rating_count: new_rating_count)
    end

    redirect_back_or(root_url)
  end

  private

    def music_params
      params.require(:music).permit(:name, :artist, :genre, :album, :cifra_link,
                                    :youtube_link, :letras_link, :spotify_track, :genre_id)
    end

    def set_music
      @music = Music.find(params[:id])
    end

    def correct_user
      if(user = @music.sent_by_id)
        @user = User.find(user)
        redirect_to(root_url) unless current_user?(@user)
      end
    end

    def search_musics(query)
      query = '%' + query.downcase + '%'

      Music.where("lower(name) LIKE ? OR lower(artist) LIKE ? OR lower(album) LIKE ?
                    OR lower(genre) LIKE ?", query, query, query, query)
    end
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/musics/_form.html.erb
<%= form_for(@music) do |f| %>
  <div class="field">
    <%= f.label :name, t('name') %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :artist, t('artist') %>
    <%= f.text_field :artist %>
  </div>

  <div class="field">
    <%= f.label :genre_id, t('genre') %>
    <%= collection_select(:music, :genre_id, Genre.all, :id, :name) %>
  </div>

  <% if !@music.new_record? %>
    <div class="field">
      <%= f.label :cifra_link, t('chords_link') %>
      <%= f.text_field :cifra_link %>
    </div>

    <div class="field">
      <%= f.label :letras_link, t('lyrics_link') %>
      <%= f.text_field :letras_link %>
    </div>

    <div class="field">
      <%= f.label :youtube_link, t('youtube_id') %>
      <%= f.text_field :youtube_link %>
    </div>

    <div class="field">
      <%= f.label :spotify_track, t('spotify_uri') %>
      <%= f.text_field :spotify_track %>
    </div>
  <% end %>

  <%= f.submit 'Salvar', class: 'btn btn' %>

  <div class="errors text-center m-10">
    <%= @music.errors.full_messages.first if @music.errors.any? %>
  </div>
<% end %>

app/views/musics/_music_list.html.erb
<div class="table">

  <div class="table-header row">
    <div class="col-xs-1">

    </div>
    <div class="col-xs-4">
      <%= t('music') %>
    </div>
    <div class="col-xs-3">
      <%= t('artist') %>
    </div>
    <div class="col-xs-2">
      <%= t('genre') %>
    </div>
  </div>

  <% @musics.each do |music| %>

    <div class="row table-line">
      <div class="col-xs-1 buttons-group text-center">
        <% if user_signed_in? %>
          <a class="dropdown-toggle" id="ddLists" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" href="#">
            <i class="fa fa-list-ul"></i>
          </a>
          <ul class="dropdown-menu" aria-labelledby="ddLists">

              <% current_user.lists.each do |list| %>
                <li> <%= link_to list.name, add_music_path(list.id, music_id: music) %> </li>
              <% end %>

          </ul>
        <% else %>
          <a id="ddLogin" href="<%= new_user_session_path %>">
            <i class="fa fa-list-ul"></i>
          </a>
        <% end %>
      </div>

      <div class="col-xs-4 nowrap">
        <%= link_to music.name, music_path(music), class: 'highlight music-name' %>
      </div>

      <div class="col-xs-3 nowrap">
        <%= music.artist %>
      </div>

      <div class="col-xs-2">
        <%= music.genre.name %>
      </div>

      <% if user_signed_in? %>

        <div class="col-xs-1 buttons-group">

          <% if @list && is_author? %>
            <%= link_to remove_music_path(@list.id, music_id: music), class: 'control-button remove-button', title: "Remover música dessa lista" do %>
              <i class="fa fa-times"></i>
            <% end %>
          <% end %>

        </div>

      <% end %>

    </div>

  <% end %>
</div>

app/views/musics/edit.html.erb
<h1>Editar música</h1>

<div class="container">
  <%= render 'form' %>
</div>

app/views/musics/index.html.erb
<div class="row">
  <%= render 'layouts/sidebar' %>
  <div class="col-xs-9 right-column">

    <div class="row text-right">
      <div class="col-xs-7 no-margin">
        <%= form_tag(musics_path, method: 'get', role: 'search') do %>
          <div class="form-group">
            <div class="input-group search">

              <%= text_field_tag(:q, params[:q], placeholder: t('search_placeholder'), class: 'search') %>

              <div class="input-group-addon">
                <%= button_tag type:'submit' do %>
                  <i class="fa fa-search"></i>
                <% end %>
              </div>

            </div>
          </div>
        <% end %>
      </div>
      <div class="col-xs-5">
          <%= will_paginate @musics %>
      </div>
    </div>

    <%= render 'music_list' %>

    <div class="row text-right">
      <%= will_paginate @musics %>
    </div>

  </div>
</div>

app/views/musics/new.html.erb
<div class="container">
  <div class="form-wrapper">
    <h2>Enviar Música</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/musics/show.html.erb
<div id="music_show">

  <h1 class='highlight music-name'>
    <%= @music.name %>
  </h1>

  <p><%= @music.artist %> / <%= @music.genre.name %></p>

  <% if user_signed_in? && current_user.admin? %>
    <%= link_to edit_music_path(@music), title: t('edit_music') do %>
      <i class="fa fa-pencil-square-o"></i>
    <% end %>

    <%= link_to music_path(@music), method: 'delete', title: t('delete_music') do %>
      <i class="fa fa-times"></i>
    <% end %>
  <% end %>

  <div class="music-content">
    <div class="col-sm-6 music-box">
      <div class="buttons-group">
        <% @music.resources.each do |resource| %>
          <a href="<%= resource.url %>" target="_blank"><%= resource.name %></a>
        <% end %>
      </div>
      <a data-toggle="modal" data-target="#modalNewResource" href="#" class="highlight">
        <%= t('send_link') %>
      </a>
    </div>

    <div class="col-sm-6">
      <% unless @music.spotify_track.nil? %>
        <div>
          <iframe src="<%= @music.spotify_iframe %>" width="300" height="80" frameborder="0" allowtransparency="true"></iframe>
        </div>
      <% end %>

      <% unless @music.youtube_link.nil? %>
        <div>
          <iframe width="380" height="300" src="<%= @music.youtube_iframe %>" frameborder="0" allowfullscreen></iframe>
        </div>
      <% end %>

    </div>
  </div>


</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modalNewResource">
  <div class="modal-dialog small-dialog">
    <div class="modal-content">
      <div class="form-wrapper">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2>Enviar Link</h2>



        <% @resource = Resource.new %>
        <%= form_for @resource do |f| %>
          <div class="field">
            <%= f.label :name, 'Nome' %>
            <%= f.text_field :name, class: 'std-input' %>
          </div>
          <div class="field">
            <%= f.label :url, 'Url:' %>
            <%= f.text_field :url, class: 'std-input' %>
          </div>

          <%= f.hidden_field :music_id, value: @music.id  %>
          <div class="actions">
              <%= f.submit 'Salvar', class: 'btn btn' %>
          </div>


        <% end %>

      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->