config/routes.rb
Rails.application.routes.draw do
  root 'musics#index'
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}
  resources :lists
  resources :musics
  resources :resources
  get 'cadastrar' => 'users#new', as: :cadastrar

  get 'lists/:id/add_music' => 'lists#add_music', as: :add_music
  get 'lists/:id/remove_music' => 'lists#remove_music', as: :remove_music

  get 'musics/:id/rate_music' => 'musics#rate_music', as: :rate_music

  get 'users/musics' => 'users#musics'

  resources :users

end

app/views/layouts/_add_list.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="modalNewList">
  <div class="modal-dialog small-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title"><%= t('new_list') %></h2>
      </div>
      <div class="modal-body">
        <% @modal_list = List.new %>

        <%= form_for @modal_list do |f| %>
          <div class="field">
            <%= f.label :name, t('name') %>
            <%= f.text_field :name %>
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox" for="is_public"> <%= t('public_list') %>
            </label>
          </div>

          <%= f.submit t('save'), class: 'btn btn' %>

        <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/_add_music.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="modalNewMusic">
  <div class="modal-dialog small-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title"><%= t('send_music') %></h2>
      </div>
      <div class="modal-body">
        <% @music = Music.new %>

        <%= form_for(@music) do |f| %>
          <div class="field">
            <%= f.label :name, t('name') %>
            <%= f.text_field :name %>
          </div>

          <div class="field">
            <%= f.label :artist, t('artist') %>
            <%= f.text_field :artist %>
          </div>

          <div class="field">
            <%= f.label :artist, t('genre') %>
            <%= collection_select(:music, :genre_id, Genre.all, :id, :name) %>
          </div>

          <% if !@music.new_record? %>
            <div class="field">
              <%= f.label :cifra_link, t('chords') %>
              <%= f.text_field :cifra_link %>
            </div>

            <div class="field">
              <%= f.label :letras_link, t('lyrics') %>
              <%= f.text_field :letras_link %>
            </div>

            <div class="field">
              <%= f.label :youtube_link, t('youtube_id') %>
              <%= f.text_field :youtube_link %>
            </div>

            <div class="field">
              <%= f.label :spotify_track, t('spotify_uri') %>
              <%= f.text_field :spotify_track %>
            </div>
          <% end %>

          <%= f.submit t('save'), class: 'btn btn' %>
        <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/_header.html.erb
<%= render 'layouts/add_music' %>

<header>
  <div class="container navbar navbar-fixed-top" id="top">
    <div class="row">
      <div class="col-xs-3 text-center">
        <!-- <a href="/">LOGO</a> -->
        <%= link_to '/' do %>
          <%= image_tag 'logo3.png', alt: 'maitabs', class: 'logo' %>

          <span class="logo-text">
            maitabs
          </span>
        <% end %>
      </div>
      <div class="col-xs-9 hidden-xs">
        <div class="col-xs-6">

        </div>
        <div class="col-xs-6">
          <div class="links-header">

            <div class="link">
              <!-- <%= link_to "Enviar Música", new_music_path, class:'highlight' %> -->
              <a data-toggle="modal" data-target="#modalNewMusic" href="#" class="highlight">
                <%= t('send_music') %>
              </a>
            </div>

            <% if(current_user) %>
              <div class="link">
                <%= link_to t('my_account'), edit_user_registration_path %>
              </div>
              <div class="link">
                <%= link_to t('logout'), destroy_user_session_path, method: "delete" %>
              </div>
            <% else %>
              <div class="link">
                <%= link_to t('login'), new_user_session_path %>
              </div>
              <div class="link">
                <%= link_to t('register'), new_user_registration_path %>
              </div>
            <% end %>

          </div>

        </div>

      </div>
    </div>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<%= render 'layouts/add_list' %>

<div class="col-xs-3 left-column">

  <% if user_signed_in? %>

    <h2><%= t('my_lists') %></h2>

    <table width="100%" class="lists">
      <% @user_lists.each do |list| %>

        <tr>
          <td>
            <%= link_to list_path(list) do %>
              <%= list.name %>
            <% end %>
          </td>
          <td class="text-right">
            <%= link_to edit_list_path(list) do %>
              <i class="fa fa-edit darker"></i>
            <% end %>
          </td>
        </tr>

      <% end %>
    </table>

    <a data-toggle="modal" data-target="#modalNewList" href="#" class="btn btn-full-width">
      <%= t('new_list') %>
    </a>
  <% else %>
    <%= t('login_to_create_lists_html', link_to_login: link_to('login', new_user_session_path, class: 'blue')) %>
    <!-- Faça <%= link_to 'login', new_user_session_path, class: 'blue' %> para criar suas listas. -->
  <% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maitabs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="main">
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>

    <!-- <%= debug(params) if Rails.env.development? %> -->
  </div>
</body>
</html>